<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="ShareefDell" failures="1" tests="1" name="Test(failed)" time="0.14" errors="0" timestamp="27 Nov 2023 10:55:02 GMT">
  <testcase classname="testNGScript.Example9" name="method1" time="0.055">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNGScript.Example9.method1(Example9.java:28)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="testNGScript.Example9" name="googleMethod" time="0.0">
    <ignored/>
  </testcase> <!-- googleMethod -->
  <testcase classname="testNGScript.Example9" name="linkedInMethod" time="0.0">
    <ignored/>
  </testcase> <!-- linkedInMethod -->
  <testcase classname="testNGScript.Example9" name="faceBookMethod" time="0.0">
    <ignored/>
  </testcase> <!-- faceBookMethod -->
</testsuite> <!-- Test(failed) -->
